version: 2

models:
  - name: stg_events
    columns:
      - name: event_id
        tests:
          - unique
          - not_null
      - name: user_id
        tests:
          - not_null
      - name: event_type
        tests:
          - not_null
          - accepted_values:
              values: ['signup', 'login', 'view_page', 'click_feature', 'upgrade_plan', 'churn']
      - name: event_timestamp
        tests:
          - not_null
      - name: platform
        tests:
          - not_null
          - accepted_values:
              values: ['mobile', 'web', 'tablet']

  - name: stg_users
    columns:
      - name: user_id
        tests:
          - unique
          - not_null
      - name: signup_date
        tests:
          - not_null
      - name: plan
        tests:
          - not_null
          - accepted_values:
              values: ['free', 'pro', 'enterprise']
      - name: platform
        tests:
          - not_null